#pragma once
#include <vector>
#include "../MODELS/Question.h"

using namespace std;

// CLASS: QUIZMANAGER
// PURPOSE: CONTROLS THE MAIN GAME FLOW, TRACKS THE USER SCORE, AND HANDLES INPUT VALIDATION
class QuizManager
{
private:
    vector<Question> questions;
    int score;
    int questionsAttempted; 

    // PURPOSE: PROMPTS THE USER FOR AN ANSWER AND STRICTLY VALIDATES IT
    // INPUT: NONE
    // OUTPUT: A VALIDATED UPPERCASE CHARACTER (A, B, C, D, OR X TO EXIT)
    // LOGIC: LOOPS CONTINUOUSLY UNTIL THE USER ENTERS A VALID CHOICE
    char getUserInput();

    // PURPOSE: SHUFFLES THE INTERNAL VECTOR OF QUESTIONS TO ENSURE A UNIQUE EXPERIENCE EVERY TIME
    // INPUT: NONE
    // OUTPUT: NONE
    // LOGIC: USES STD::SHUFFLE WITH A HARDWARE-BASED RANDOM SEED
    void randomizeQuestions();

public:
    // PURPOSE: CONSTRUCTOR TO INITIALIZE THE QUIZ MANAGER
    // INPUT: A VECTOR OF LOADED QUESTION OBJECTS
    // OUTPUT: NONE
    // LOGIC: COPIES THE QUESTIONS AND INITIALIZES THE SCORE AND ATTEMPTS TO ZERO
    QuizManager(const vector<Question>& loadedQuestions);

    // PURPOSE: STARTS AND RUNS THE MAIN QUIZ LOOP
    // INPUT: NONE
    // OUTPUT: NONE
    // LOGIC: RANDOMIZES QUESTIONS, ITERATES THROUGH THEM, ALLOWS EARLY EXIT, AND UPDATES SCORE
    void start();

    // PURPOSE: DISPLAYS THE FINAL SCORE, PERCENTAGE, AND PASS/FAIL STATUS
    // INPUT: NONE
    // OUTPUT: PRINTS FORMATTED RESULTS TO THE CONSOLE
    // LOGIC: CALCULATES PERCENTAGE BASED ON ATTEMPTED QUESTIONS TO AVOID DIVIDE-BY-ZERO
    void displayResults() const;
};