#pragma once
#include <vector>
#include "../MODELS/Question.h"

using namespace std;

// CLASS: QUIZMANAGER
// PURPOSE: CONTROLS THE MAIN GAME FLOW, TRACKS THE USER SCORE, AND HANDLES INPUT VALIDATION
class QuizManager
{
private:
    vector<Question> questions;
    int score;

    // PURPOSE: PROMPTS THE USER FOR AN ANSWER AND STRICTLY VALIDATES IT
    // INPUT: NONE
    // OUTPUT: A VALIDATED UPPERCASE CHARACTER (A, B, C, OR D)
    // LOGIC: LOOPS CONTINUOUSLY UNTIL THE USER ENTERS A VALID CHOICE
    char getUserInput();

public:
    // PURPOSE: CONSTRUCTOR TO INITIALIZE THE QUIZ MANAGER
    // INPUT: A VECTOR OF LOADED QUESTION OBJECTS
    // OUTPUT: NONE
    // LOGIC: COPIES THE QUESTIONS AND INITIALIZES THE SCORE TO ZERO
    QuizManager(const vector<Question>& loadedQuestions);

    // PURPOSE: STARTS AND RUNS THE MAIN QUIZ LOOP
    // INPUT: NONE
    // OUTPUT: NONE
    // LOGIC: ITERATES THROUGH ALL QUESTIONS, DISPLAYS THEM, PROCESSES INPUT, AND UPDATES SCORE
    void start();

    // PURPOSE: DISPLAYS THE FINAL SCORE, PERCENTAGE, AND PASS/FAIL STATUS
    // INPUT: NONE
    // OUTPUT: PRINTS FORMATTED RESULTS TO THE CONSOLE
    // LOGIC: CALCULATES PERCENTAGE USING DOUBLE CASTING AND EVALUATES PASS/FAIL
    void displayResults() const;
};