#pragma once
#include <vector>
#include "../MODELS/Question.h"

using namespace std;

// STRUCT: ANSWERRECORD
// PURPOSE: A DATA STRUCTURE TO HOLD THE HISTORY OF THE USER'S ATTEMPT FOR A SPECIFIC QUESTION
struct AnswerRecord
{
    Question question;
    char userAnswer;
    bool isCorrect;
    double timeTaken;
    bool wasTimeout;
};

// CLASS: QUIZMANAGER
// PURPOSE: CONTROLS THE MAIN GAME FLOW, TRACKS THE USER SCORE, LOGS HISTORY, AND HANDLES TIMERS
class QuizManager
{
private:
    vector<Question> questions;
    vector<AnswerRecord> attemptHistory; // NEW: STORES THE DETAILS OF EVERY ANSWER GIVEN
    int score;
    int questionsAttempted; 
    const double TIME_LIMIT_SECONDS = 15.0; // NEW: STRICT TIME LIMIT PER QUESTION

    // PURPOSE: PROMPTS THE USER FOR AN ANSWER AND STRICTLY VALIDATES IT
    // INPUT: NONE
    // OUTPUT: A VALIDATED UPPERCASE CHARACTER (A, B, C, D, OR X TO EXIT)
    // LOGIC: LOOPS CONTINUOUSLY UNTIL THE USER ENTERS A VALID CHOICE
    char getUserInput();

    // PURPOSE: SHUFFLES THE INTERNAL VECTOR OF QUESTIONS TO ENSURE A UNIQUE EXPERIENCE EVERY TIME
    // INPUT: NONE
    // OUTPUT: NONE
    // LOGIC: USES STD::SHUFFLE WITH A HARDWARE-BASED RANDOM SEED
    void randomizeQuestions();

    // PURPOSE: PROMPTS THE USER IF THEY WANT TO SEE THEIR INCORRECT ANSWERS
    // INPUT: NONE
    // OUTPUT: PRINTS OUT DETAILED HISTORY OF WRONG ANSWERS
    // LOGIC: FILTERS THE ATTEMPTHISTORY VECTOR FOR INCORRECT ENTRIES AND PRINTS THEM
    void showIncorrectAnswers() const;

public:
    // PURPOSE: CONSTRUCTOR TO INITIALIZE THE QUIZ MANAGER
    // INPUT: A VECTOR OF LOADED QUESTION OBJECTS
    // OUTPUT: NONE
    // LOGIC: COPIES THE QUESTIONS AND INITIALIZES THE SCORE AND ATTEMPTS TO ZERO
    QuizManager(const vector<Question>& loadedQuestions);

    // PURPOSE: STARTS AND RUNS THE MAIN QUIZ LOOP
    // INPUT: NONE
    // OUTPUT: NONE
    // LOGIC: RANDOMIZES QUESTIONS, USES CHRONO FOR TIMING, LOGS HISTORY, AND UPDATES SCORE
    void start();

    // PURPOSE: DISPLAYS THE FINAL SCORE, PERCENTAGE, PASS/FAIL STATUS, AND OPTIONAL REVIEW
    // INPUT: NONE
    // OUTPUT: PRINTS FORMATTED RESULTS TO THE CONSOLE
    // LOGIC: CALCULATES PERCENTAGE BASED ON ATTEMPTED QUESTIONS TO AVOID DIVIDE-BY-ZERO
    void displayResults() const;
};