#pragma once
#include <vector>
#include <string>
#include "../MODELS/Question.h"

using namespace std;

// CLASS: FILELOADER
// PURPOSE: UTILITY CLASS TO HANDLE ALL FILE I/O (READING QUESTIONS AND SAVING SCORES)
class FileLoader
{
public:
    // PURPOSE: READS THE SPECIFIED FILE AND CONVERTS TEXT BLOCKS INTO QUESTION OBJECTS
    // INPUT: CONSTANT REFERENCE TO A STRING REPRESENTING THE FILE PATH
    // OUTPUT: A VECTOR CONTAINING ALL PARSED QUESTION OBJECTS
    // LOGIC: OPENS FILE, EXTRACTS TEXT LINE BY LINE, BUILDS QUESTION OBJECTS, AND HANDLES MISSING FILES
    static vector<Question> loadQuestions(const string& filePath);

    // PURPOSE: APPENDS THE PLAYER'S SCORE TO THE HIGH SCORES TEXT FILE
    // INPUT: CONSTANT REFERENCE TO THE PLAYER'S NAME, THEIR SCORE, AND QUESTIONS ATTEMPTED
    // OUTPUT: NONE (WRITES DIRECTLY TO FILE)
    // LOGIC: OPENS FILE IN APPEND MODE (IOS::APP) TO PREVENT OVERWRITING PAST SCORES
    static void saveScore(const string& playerName, int score, int attempted);
};