#pragma once
#include <vector>
#include <string>
#include "../MODELS/Question.h"

using namespace std;

// CLASS: FILELOADER
// PURPOSE: UTILITY CLASS TO READ AND PARSE THE QUESTIONS TEXT FILE.
class FileLoader
{
public:
    // PURPOSE: READS THE SPECIFIED FILE AND CONVERTS TEXT BLOCKS INTO QUESTION OBJECTS
    // INPUT: CONSTANT REFERENCE TO A STRING REPRESENTING THE FILE PATH
    // OUTPUT: A VECTOR CONTAINING ALL PARSED QUESTION OBJECTS
    // LOGIC: OPENS FILE, EXTRACTS TEXT LINE BY LINE, BUILDS QUESTION OBJECTS, AND HANDLES MISSING FILES
    static vector<Question> loadQuestions(const string& filePath);
};