#pragma once
#include <vector>
#include <string>
#include "../MODELS/Question.h"

using namespace std;

// CLASS: FILELOADER
// PURPOSE: UTILITY CLASS TO HANDLE ALL FILE I/O (READING QUESTIONS, SAVING SCORES WITH TIMESTAMPS, AND LEADERBOARDS)
class FileLoader
{
public:
    // PURPOSE: READS THE SPECIFIED FILE AND CONVERTS TEXT BLOCKS INTO QUESTION OBJECTS
    // INPUT: CONSTANT REFERENCE TO A STRING REPRESENTING THE FILE PATH
    // OUTPUT: A VECTOR CONTAINING ALL PARSED QUESTION OBJECTS
    // LOGIC: OPENS FILE, EXTRACTS TEXT LINE BY LINE, BUILDS QUESTION OBJECTS, AND HANDLES MISSING FILES
    static vector<Question> loadQuestions(const string& filePath);

    // PURPOSE: APPENDS THE PLAYER'S SCORE AND CURRENT TIMESTAMP TO THE HIGH SCORES TEXT FILE
    // INPUT: CONSTANT REFERENCE TO THE PLAYER'S NAME, THEIR SCORE, AND QUESTIONS ATTEMPTED
    // OUTPUT: NONE (WRITES DIRECTLY TO FILE)
    // LOGIC: OPENS FILE IN APPEND MODE (IOS::APP), FETCHES SYSTEM TIME, AND PREVENTS OVERWRITING PAST SCORES
    static void saveScore(const string& playerName, int score, int attempted);

    // PURPOSE: READS THE HIGH SCORES FILE, SORTS BY PERCENTAGE, AND DISPLAYS THE TOP 5 PLAYERS
    // INPUT: NONE
    // OUTPUT: PRINTS A FORMATTED LEADERBOARD TO THE CONSOLE
    // LOGIC: PARSES FILE STRINGS, CONVERTS TO INTEGERS, CALCULATES PERCENTAGES, AND SORTS DESCENDING
    static void displayTopHighScores();
};